export const COMMAND_MACROS = [
  "mstr", "display_mstr", "LOW_IQ", "Reply", "Reply_Rand", "GMessage", "NMessage", "BMessage",
  "GOption", "NOption", "BOption", "Option", "critter_is_armed", "critter_weight", "critter_wearing_armor",
  "dude_name", "dude_gender", "dude_is_male", "dude_is_female", "dude_is_armed", "dude_wearing_armor",
  "dude_has_perm_stink", "dude_has_the_stink", "dude_stinks", "update_the_stink", "increase_the_stink",
  "remove_the_stink", "roll_vs_intimidate", "Get_Rotation_Away_From_Dude", "Run_Away_From_Dude_Dir",
  "run_away_from_dist", "push_away_from_dist", "run_away_tile_dir", "Run_Away_From_Dude_Tile",
  "Current_Distance_From_Dude", "Future_Distance_From_Obj", "Future_Distance_From_Dude", "away_from_tile_type",
  "simulate_push", "flee_from_tile", "Flee_From_Dude", "Flee_From_Dude_Force", "Follow_Dude",
  "get_follow_point_dist", "follow_obj_point", "follow_dude_point", "Follow_Dude_Run_Only",
  "Follow_Obj_Run_Only", "Get_In_Obj_Face", "Get_In_Face_Run_Dist", "next_and_face_obj",
  "point_next_and_face_obj", "Get_Next_To_Obj_And_Face_Rate", "Get_Next_To_Obj_And_Face",
  "Run_Next_To_Obj_And_Face_Rate", "Run_Next_To_Obj_And_Face", "point_move_next_and_face_Rate",
  "point_move_next_and_face", "point_run_next_and_face_Rate", "point_run_next_and_face", "closest_clear_tile",
  "FAIL_STEP_ACTION", "move_to_point", "anim_move_to_point_rate", "anim_move_to_point",
  "anim_run_to_point_rate", "anim_run_to_point", "dude_is_stupid", "dude_strength", "dude_perception",
  "dude_endurance", "dude_charisma", "dude_iq", "dude_agility", "dude_luck", "dude_level", "dude_age",
  "dude_weight", "dude_moron_not_vegetable", "dude_has_power_armor", "dude_wielding_knife",
  "dude_wearing_power_armor", "dude_wearing_leather_armor", "dude_wearing_combat_armor",
  "dude_wearing_metal_armor", "dude_wearing_vault_suit", "dude_has_gambling_skills", "dude_is_sneaking",
  "dude_is_walking", "dude_is_running", "dude_is_poisoned", "dude_is_irradiated", "dude_is_crippled",
  "dude_cur_rot", "dude_inv_rot", "dude_tile", "dude_elevation", "tile_behind_obj", "tile_behind_obj_rng",
  "dude_cur_hits", "dude_max_hits", "dude_mental_block", "dude_presence", "dude_awareness",
  "dude_fortune_finder", "dude_smooth_talker", "dude_caps", "dude_has_car", "dude_is_pornstar",
  "dude_is_high", "dude_found_geck", "dude_stat_win", "dude_stat_lose", "dude_stat_tie", "dude_can_see_self",
  "dude_item", "dude_item_count", "dude_is_addict", "spouse_none", "spouse_female", "spouse_male",
  "dude_spouse_is_male", "dude_spouse_is_female", "dude_is_married", "set_dude_married",
  "dude_spouse_was_male", "dude_spouse_was_female", "dude_was_married", "set_dude_was_married", "floater",
  "floater_rand", "FLOAT_COLOR_NORMAL", "FLOAT_COLOR_SICK", "FLOAT_COLOR_BAD", "FLOAT_COLOR_GOOD",
  "FLOAT_COLOR_SFX", "FLOAT_COLOR_SAD", "FLOAT_COLOR_AFRAID", "FLOAT_COLOR_PAIN", "FLOAT_COLOR_HIGH",
  "FLOAT_COLOR_WHISPER", "self_attack_dude", "self_name", "self_gender", "self_strength", "self_perception",
  "self_endurance", "self_charisma", "self_iq", "self_agility", "self_luck", "self_is_male", "self_is_female",
  "self_is_armed", "self_wearing_armor", "self_carrying_laser_pistol", "self_is_sneaking", "self_is_walking",
  "self_is_running", "self_is_poisoned", "self_cur_rot", "self_inv_rot", "self_tile", "self_elevation",
  "self_pid", "self_team", "self_ai", "self_visible", "self_cur_hits", "self_max_hits", "self_mental_block",
  "self_presence", "self_awareness", "self_fortune_finder", "self_caps", "self_fid", "skill_success",
  "stat_success", "self_can_see_dude", "self_distance_from_dude", "self_is_high", "self_item",
  "self_item_count"
];
